# Copyright (C) 2017-2018 Project-ODE
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


# Hyperswitch configuration for ODE-FeatureService api:annotation-set endpoints
# Author: Erwan Keribin


swagger: '2.0'
info:
  version: '1.0.0-beta'
  title: ODE FeatureService Annotation Task API
  description: ODE FeatureService Annotation Task API
  termsofservice: TBD
  contact:
    name: ODE-Project Team
    email: TBD
    url: TBD
  license:
    name: GNU General Public Licence, v3
    url: https://www.gnu.org/licenses/gpl-3.0.en.html
paths:
  /campaign/{id}/my-list:
    get:
      tags:
        - ODE FeatureService annotation task listing function
      summary: Lists annotation tasks for a given campaign-id and currently logged-in user
      description: |
        Returns a list of the currently logged-in user annotation tasks for the identified campaign
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: Annotation Campaign ID
          type: integer
          required: true
      responses:
        '200':
          description: list of user campaign annotation tasks
          schema:
            $ref: '#/definitions/annotation-task-list'
        default:
          description: Error
          schema:
            $ref: '#/definitions/problem'
      x-request-handler:
        - verify_token:
            request:
              method: 'get'
              uri: /{domain}/sys/authentication/verify-token
              headers: '{{request.headers}}'
            return_if:
              status: ['4xx', '5xx']
        - get_from_backend:
            request:
              uri: /{domain}/sys/annotation-task/campaign/{id}/my-list
              current_user: '{{verify_token.body.token.aud}}'
      x-monitor: false

  /{id}:
    get:
      tags:
        - ODE FeatureService annotation task audio annotator
      summary: Returns the output needed for the audio annotator to work on the specified annotation task
      description: |
        Returns the info needed for the audio annotator to work on the specified annotation task
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: Annotation Task ID
          type: integer
          required: true
      responses:
        '200':
          description: audio annotator input
          schema:
            $ref: '#/definitions/audio-annotator-input'
        default:
          description: Error
          schema:
            $ref: '#/definitions/problem'
      x-request-handler:
        - verify_token:
            request:
              method: 'get'
              uri: /{domain}/sys/authentication/verify-token
              headers: '{{request.headers}}'
            return_if:
              status: ['4xx', '5xx']
        - get_from_backend:
            request:
              uri: /{domain}/sys/annotation-task/{id}
              current_user: '{{verify_token.body.token.aud}}'
      x-monitor: false

  /legacy/{id}:
    get:
      tags:
        - ODE FeatureService annotation task legacy audio annotator
      summary: Returns the output needed for the legacy audio annotator to work on the specified annotation task
      description: |
        Returns the info needed for the legacy audio annotator to work on the specified annotation task
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: Annotation Task ID
          type: integer
          required: true
      responses:
        '200':
          description: legacy audio annotator input
          schema:
            $ref: '#/definitions/legacy-audio-annotator-input'
        default:
          description: Error
          schema:
            $ref: '#/definitions/problem'
      x-request-handler:
        - verify_token:
            request:
              method: 'get'
              uri: /{domain}/sys/authentication/verify-token
              headers: '{{request.headers}}'
            return_if:
              status: ['4xx', '5xx']
        - get_from_backend:
            request:
              uri: /{domain}/sys/annotation-task/legacy/{id}
              current_user: '{{verify_token.body.token.aud}}'
      x-monitor: false

  /{id}/update-results:
    post:
      tags:
        - ODE FeatureService annotation task audio annotator post
      summary: Updates result for specified annotation task, will return next task ID
      description: |
        Updates result for specified annotation task with AudioAnnotator format, will return next task ID
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: Annotation Task ID
          type: integer
          required: true
        - name: task_start_time
          in: formData
          description: Start time of annotation session
          type: integer
          required: true
        - name: task_end_time
          in: formData
          description: End time of annotation sessions
          type: integer
          required: true
        - name: visualization
          in: formData
          description: Task visualization type
          type: string
          required: false
        - name: annotations
          in: formData
          description: Result annotations
          schema:
            $ref: '#/definitions/annotations'
          required: true
        - name: deleted_annotations
          in: formData
          description: Deleted annotations
          schema:
            $ref: '#/definitions/annotations'
          required: false
        - name: annotation_events
          in: formData
          description: List of the different types of actions they took to create the annotations
          schema:
            $ref: '#/definitions/annotation-events'
          required: false
        - name: play_events
          in: formData
          description: List of actions the user took to play and pause the audio
          schema:
            $ref: '#/definitions/play-events'
          required: false
        - name: final_solution_shown
          in: formData
          description: Boolean, if at the end, the user was shown what city the clip was recorded in
          type: boolean
          required: false
      responses:
        '200':
          description: next task ID or campaign ID if there are no more tasks
          schema:
            $ref: '#/definitions/audio-annotator-next'
        default:
          description: Error
          schema:
            $ref: '#/definitions/problem'
      x-request-handler:
        - verify_token:
            request:
              method: 'get'
              uri: /{domain}/sys/authentication/verify-token
              headers: '{{request.headers}}'
            return_if:
              status: ['4xx', '5xx']
        - post_to_backend:
            request:
              method: post
              uri: /{domain}/sys/annotation-task/{id}/update-results
              headers:
                content-type: multipart/form-data
              body:
                task_start_time: '{{task_start_time}}'
                task_end_time: '{{task_end_time}}'
                visualization: '{{visualization}}'
                annotations: '{{annotations}}'
                deleted_annotations: '{{deleted_annotations}}'
                annotation_events: '{{annotation_events}}'
                play_events: '{{play_events}}'
                final_solution_shown: '{{final_solution_shown}}'
              current_user: '{{verify_token.body.token.aud}}'
      x-monitor: false

definitions:
  # A https://tools.ietf.org/html/draft-nottingham-http-problem
  problem:
    required:
      - type
    properties:
      type:
        type: string
      title:
        type: string
      detail:
        type: string
      instance:
        type: string

  annotations:
    type: array
    items:
      properties:
        id:
          type: string
        annotation:
          type: string
        startTime:
          type: number
        endTime:
          type: number
        startFrequency:
          type: number
        endFrequency:
          type: number

  annotation-events:
    type: array
    items:
      properties:
        event:
          type: string
        region_id:
          type: string
        time:
          type: integer
        region_start:
          type: number
        region_end:
          type: number
        region_label:
          type: string

  annotation-task-list:
    type: array
    items:
      properties:
        id:
          type: integer
        status:
          type: integer
        filename:
          type: string
        dataset_name:
          type: string
        start:
          type: string
        end:
          type: string

  audio-annotator-input:
    properties:
      campaignId:
        type: number
      annotationTags:
        type: array
        items:
          type: string
      boundaries:
        properties:
          startTime:
            type: string
          endTime:
            type: string
          startFrequency:
            type: number
          endFrequency:
            type: number
      audioUrl:
        type: string
      audioRate:
        type: number
      spectroUrls:
        type: array
        items:
          properties:
            urls:
              type: array
              items:
                type: string
          additionalProperties:
            type: string
      prevAnnotations:
        $ref: '#/definitions/annotations'
      instructionsUrl:
        type: string
      startZoom:
        type: number
      filename:
        type: string
      presenceTask:
        type: boolean

  legacy-audio-annotator-input:
    properties:
      feedback:
        type: string
      visualization:
        type: string
      proximityTag:
        type: array
        items:
          type: string
      annotationTag:
        type: array
        items:
          type: string
      url:
        type: string
      alwaysShowTags:
        type: boolean

    audio-annotator-next:
      properties:
        next_task:
          type: integer
        campaign_id:
          type: integer

  play-events:
    type: array
    items:
      properties:
        audioSourceTime:
          type: number
        event:
          type: string
        time:
          type: integer
