# Copyright (C) 2017-2018 Project-ODE
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


# Hyperswitch configuration for ODE-FeatureService api:annotation campaign endpoints
# Author: Erwan Keribin


swagger: '2.0'
info:
  version: '1.0.0-beta'
  title: ODE FeatureService Annotation Campaign API
  description: ODE FeatureService Annotation Campaign API
  termsofservice: TBD
  contact:
    name: ODE-Project Team
    email: TBD
    url: TBD
  license:
    name: GNU General Public Licence, v3
    url: https://www.gnu.org/licenses/gpl-3.0.en.html
paths:

  /{id}:
    get:
      tags:
        - ODE FeatureService annotation campaign detail
      summary: Returns details of a specific annotation campaign
      description: |
        Returns details of a specific annotation campaign
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: Annotation Campaign ID
          type: integer
          required: true
      responses:
        '200':
          description: details of a specific annotation campaign
          schema:
            $ref: '#/definitions/annotation-campaign-detail'
        default:
          description: Error
          schema:
            $ref: '#/definitions/problem'
      x-request-handler:
        - verify_token:
            request:
              method: 'get'
              uri: /{domain}/sys/authentication/verify-token
              headers: '{{request.headers}}'
            return_if:
              status: ['4xx', '5xx']
        - get_from_backend:
            request:
              uri: /{domain}/sys/annotation-campaign/{id}
      x-monitor: false

  /list:
    get:
      tags:
        - ODE FeatureService annotation campaign list
      summary: Lists all annotation campaigns
      description: |
        Returns a list of all annotation campaigns with relevant information
      produces:
        - application/json
      responses:
        '200':
          description: list of all annotation campaigns
          schema:
            $ref: '#/definitions/annotation-campaign-list'
        default:
          description: Error
          schema:
            $ref: '#/definitions/problem'
      x-request-handler:
        - verify_token:
            request:
              method: 'get'
              uri: /{domain}/sys/authentication/verify-token
              headers: '{{request.headers}}'
            return_if:
              status: ['4xx', '5xx']
        - get_from_backend:
            request:
              uri: /{domain}/sys/annotation-campaign/list
              current_user: '{{verify_token.body.token.aud}}'
      x-monitor: false

  /new:
    post:
      tags:
        - ODE FeatureService annotation campaign create
      summary: Create a new annotation campaign
      description: |
        Returns the created annotation campaign
      produces:
        - application/json
      parameters:
        - name: name
          in: formData
          description: Name for the new annotation campaign
          type: string
          required: true
        - name: desc
          in: formData
          description: Description for the new annotation campaign
          type: string
          required: true
        - name: datasets
          in: formData
          description: Array containing datasets id targeted by the new annotation campaign
          type: array
          items:
            type: integer
          required: true
        - name: start
          in: formData
          description: Start date for the new annotation campaign
          type: string
          required: true
        - name: end
          in: formData
          description: End date for the new annotation campaign
          type: string
          required: true
        - name: annotation_set
          in: formData
          description: Annotation set id chosen for the new annotation campaign
          type: integer
          required: true
        - name: annotators
          in: formData
          description: Array containing users id chosen as annotators for the new annotation campaign
          type: array
          items:
            type: integer
          required: true
        - name: annotation_goal
          in: formData
          description: Number of wanted annotations per file in the new annotation campaign
          type: integer
          required: true
        - name: annotation_method
          in: formData
          description: Distribution method of files to annotate for the new annotation campaign (0 for Random and 1 for Sequential)
          type: integer
          minimum: 0
          maximum: 1
          required: true
      responses:
        '200':
          description: the newly created annotation campaign
          schema:
            $ref: '#/definitions/annotation-campaign'
        default:
          description: Error
          schema:
            $ref: '#/definitions/problem'
      x-request-handler:
        - verify_token:
            request:
              method: get
              uri: /{domain}/sys/authentication/verify-token
              headers: '{{request.headers}}'
            return_if:
              status: ['4xx', '5xx']
        - post_to_backend:
            request:
              method: post
              uri: /{domain}/sys/annotation-campaign/new
              headers:
                content-type: multipart/form-data
              body:
                name: '{{name}}'
                desc: '{{desc}}'
                start: '{{start}}'
                end: '{{end}}'
                annotation_set: '{{annotation_set}}'
                datasets: '{{datasets}}'
                annotators: '{{annotators}}'
                annotation_goal: '{{annotation_goal}}'
                annotation_method: '{{annotation_method}}'
              current_user: '{{verify_token.body.token.aud}}'
      x-monitor: false

  /report/{id}:
    get:
      tags:
        - ODE FeatureService annotation campaign csv report
      summary: Returns the CSV report of a specific annotation campaign
      description: |
        Returns the CSV report of a specific annotation campaign
      produces:
        - text/csv
      parameters:
        - name: id
          in: path
          description: Annotation Campaign ID
          type: integer
          required: true
      responses:
        '200':
          description: CSV report of a specific annotation campaign
          schema:
            type: string
        default:
          description: Error
          schema:
            $ref: '#/definitions/problem'
      x-request-handler:
        - verify_token:
            request:
              method: 'get'
              uri: /{domain}/sys/authentication/verify-token
              headers: '{{request.headers}}'
            return_if:
              status: ['4xx', '5xx']
        - get_from_backend:
            request:
              uri: /{domain}/sys/annotation-campaign/report/{id}
      x-monitor: false

definitions:
  # A https://tools.ietf.org/html/draft-nottingham-http-problem
  problem:
    required:
      - type
    properties:
      type:
        type: string
      title:
        type: string
      detail:
        type: string
      instance:
        type: string

  annotation-campaign:
    properties:
      id:
        type: integer
      name:
        type: string
      start:
        type: string
      end:
        type: string
      annotation_set_id:
        type: integer
      owner_id:
        type: integer
      datasets:
        type: array
        items:
          properties:
            id:
              type: integer
      annotation_tasks:
        type: array
        items:
          properties:
            id:
              type: integer
            status:
              type: integer
            dataset_file_id:
              type: integer
            annotator_id:
              type: integer
            annotation_campaign_id:
              type: integer

  annotation-campaign-detail:
    properties:
      campaign:
        properties:
          id:
            type: integer
          name:
            type: string
          start:
            type: string
          end:
            type: string
          owner_id:
            type: integer
        type: integer
      tasks:
        type: array
        items:
          properties:
            count:
              type: integer
            annotator_id:
              type: integer
            status:
              type: integer

  annotation-campaign-list:
    type: array
    items:
      properties:
        id:
          type: integer
        name:
          type: string
        start:
          type: string
        end:
          type: string
        annotation_set_id:
          type: integer
        tasks_count:
          type: integer
        user_tasks_count:
          type: integer
        complete_tasks_count:
          type: integer
        user_complete_tasks_count:
          type: integer
        datasets_count:
          type: integer
