# Copyright (C) 2017-2018 Project-ODE
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


# Hyperswitch configuration for ODE-FeatureService api:dataset endpoints
# Author: Erwan Keribin


swagger: '2.0'
info:
  version: '1.0.0-beta'
  title: ODE FeatureService Dataset API
  description: ODE FeatureService Dataset API
  termsofservice: TBD
  contact:
    name: ODE-Project Team
    email: TBD
    url: TBD
  license:
    name: GNU General Public Licence, v3
    url: https://www.gnu.org/licenses/gpl-3.0.en.html
paths:
  /list:
    get:
      tags:
        - ODE FeatureService dataset listing function
      summary: Lists all datasets
      description: |
        Returns a list of all datasets with relevant information
      produces:
        - application/json
      responses:
        '200':
          description: list of all datasets
          schema:
            $ref: '#/definitions/dataset-list'
        default:
          description: Error
          schema:
            $ref: '#/definitions/problem'
      x-request-handler:
        - get_from_backend:
            request:
              uri: /{domain}/sys/dataset/list
      x-monitor: false

definitions:
  # A https://tools.ietf.org/html/draft-nottingham-http-problem
  problem:
    required:
      - type
    properties:
      type:
        type: string
      title:
        type: string
      detail:
        type: string
      instance:
        type: string

  dataset-list:
    type: array
    items:
      properties:
        id:
          type: integer
        name:
          type: string
        files_type:
          type: string
        start_date:
          type: string
        end_date:
          type: string
        type:
          type: string
        files_count:
          type: integer
