#
# Hyperswitch configuration for EBDO-FeatureService api:examples endpoints
# Copyright (C) 2017 Project-EBDO
# Author: Joseph Allemandou
#
swagger: '2.0'
info:
  version: '1.0.0-beta'
  title: EBDO FeatureService Examples API
  description: EBDO FeatureService Examples API
  termsofservice: TBD
  contact:
    name: EBDO-Project Team
    email: TBD
    url: TBD
  license:
    name: GNU General Public Licence, v3
    url: https://www.gnu.org/licenses/gpl-3.0.en.html
paths:
  /:
    get:
      tags:
        - EBDO FeatureService Examples
      summary: List EBDO FeatureService API entry points
      description: |
        This is the root of the EBDO FeatureService Examples
      produces:
        - application/json
      responses:
        '200':
          description: The queriable sub-items
          schema:
            $ref: '#/definitions/listing'
        default:
          description: Error
          schema:
            $ref: '#/definitions/problem'
      x-monitor: false

  /fake-timeserie/{from}/{to}/{step}:
    get:
      tags:
        - EBDO FeatureService Examples
      summary: Get a fake timeserie
      description: |
        Get a fake timeserie with random [0, 1[ values in [from, to[ interval by step
      produces:
        - application/json
      parameters:
        - name: from
          in: path
          description: Starting date-time of the timeserie, inclusive. Expecting YYYY-MM-DD or YYYY-MM-DDTHH:MM:SS formats.
          type: string
          required: true
        - name: to
          in: path
          description: Ending date-time of the timeserie, exclusive. Expecting YYYY-MM-DD or YYYY-MM-DDTHH:MM:SS formats.
          type: string
          required: true
        - name: step
          in: path
          description: The step in time unit for generated random data. Can be second, minute, hour or day.
          type: string
          enum: ['second', 'minute', 'hour', 'day']
          required: true
      responses:
        '200':
          description: The list of timestamps and generated random values
          schema:
            $ref: '#/definitions/fake-timeserie'
        default:
          description: Error
          schema:
            $ref: '#/definitions/problem'
      x-request-handler:
        - get_from_backend:
            request:
              uri: /{domain}/sys/examples/fake-timeserie/{from}/{to}/{step}
      x-monitor: false

definitions:
  # A https://tools.ietf.org/html/draft-nottingham-http-problem
  problem:
    required:
      - type
    properties:
      type:
        type: string
      title:
        type: string
      detail:
        type: string
      instance:
        type: string

  listing:
    description: The result format for listings
    required:
      - items
    properties:
      items:
        type: array
        items:
          type: string

  fake-timeserie:
    properties:
      items:
        type: array
        items:
          properties:
            ts:
              type : string
            val:
              type: double
