# Copyright (C) 2017-2018 Project-ODE
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


# Hyperswitch configuration for ODE-FeatureService api:authentication endpoints
# Author: Erwan Keribin


swagger: '2.0'
info:
  version: '1.0.0-beta'
  title: ODE FeatureService Authentication API
  description: ODE FeatureService Authentication API
  termsofservice: TBD
  contact:
    name: ODE-Project Team
    email: TBD
    url: TBD
  license:
    name: GNU General Public Licence, v3
    url: https://www.gnu.org/licenses/gpl-3.0.en.html
paths:
  /datasets:
    get:
      tags:
        - ODE FeatureService authentication function
      summary: Authenticate user
      description: |
        Authenticate user from credentials, returning a JWT token on authentication success
      produces:
        - application/json
      responses:
        '200':
          description: session token
        default:
          description: Error
          schema:
            $ref: '#/definitions/problem'
      x-request-handler:
        - get_from_backend:
            request:
              uri: /{domain}/sys/front_manager/datasets
      x-monitor: false

  /annotation_campaigns:
    get:
      tags:
        - ODE FeatureService authentication function
      summary: Authenticate user
      description: |
        Authenticate user from credentials, returning a JWT token on authentication success
      produces:
        - application/json
      responses:
        '200':
          description: session token
        default:
          description: Error
          schema:
            $ref: '#/definitions/problem'
      x-request-handler:
        - get_from_backend:
            request:
              uri: /{domain}/sys/front_manager/annotation_campaigns
      x-monitor: false

  /create_annotation_campaign:
    get:
      tags:
        - ODE FeatureService authentication function
      summary: Authenticate user
      description: |
        Authenticate user from credentials, returning a JWT token on authentication success
      produces:
        - application/json
      responses:
        '200':
          description: session token
        default:
          description: Error
          schema:
            $ref: '#/definitions/problem'
      x-request-handler:
        - get_from_backend:
            request:
              uri: /{domain}/sys/front_manager/create_annotation_campaign
      x-monitor: false
    post:
      tags:
        - ODE FeatureService authentication function
      summary: Authenticate user
      description: |
        Authenticate user from credentials, returning a JWT token on authentication success
      produces:
        - application/json
      parameters:
        - name: name
          in: formData
          description: User login
          type: string
          required: true
        - name: desc
          in: formData
          description: User password
          type: string
          required: true
        - name: datasets
          in: formData
          description: User password
          required: true
          schema:
            type: array
            items:
              type: integer
        - name: start
          in: formData
          description: User password
          type: string
          required: true
        - name: end
          in: formData
          description: User password
          type: string
          required: true
        - name: annotation_set
          in: formData
          description: User password
          type: integer
          required: true
      responses:
        '200':
          description: session token
        default:
          description: Error
          schema:
            $ref: '#/definitions/problem'
      x-request-handler:
        - post_to_backend:
            request:
              method: post
              uri: /{domain}/sys/front_manager/create_annotation_campaign
              headers:
                content-type: multipart/form-data
              body:
                name: '{{name}}'
                desc: '{{desc}}'
                start: '{{start}}'
                end: '{{end}}'
                annotation_set_id: '{{annotation_set}}'
                datasets: '{{datasets}}'
      x-monitor: false

definitions:
  # A https://tools.ietf.org/html/draft-nottingham-http-problem
  problem:
    required:
      - type
    properties:
      type:
        type: string
      title:
        type: string
      detail:
        type: string
      instance:
        type: string
