language: node_js
node_js:
  - '9'
sudo: false
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
    - postgresql-10-postgis-2.4 
    - postgresql-10-postgis-scripts
env:
  global:
  - PGPORT=5433
services:
  - postgresql
before_script:
  - psql -U travis -c "CREATE USER test WITH PASSWORD 'password';"
  - psql -U travis -c "CREATE DATABASE test OWNER test;"
  - psql -U travis -d test -c "CREATE EXTENSION postgis;"
script: sh test/utils/run_tests.sh coverage all && (npm run-script coveralls || exit 0)
notifications:
  slack:
    secure: "ZWrJIfKPTM6puZsn+PF85JVVQT4xeq2rWa5N1t+nVYIXZ/zsr0VGwTO4aC0Y4JqtGv5DYjoIBPEnw/AYg7staD2IEwiDCSk6awT8MxlInlc2cYHIthB2y/qXLCVgG+DCC/bUMXQ816XUokEIaISnNhy9axA92Y8BSGafhmqJfqrRSKp0I0z9NXvyXj+dbHFkh01h9yot99SeXcVi4LXUAeGJcX2EecugH55Z8TYvbfqG1Vw/G37EMzlFGvx6wTLfyrSae2VAzLvz3uUBqiak+PMJUu1rTjw8Yrqhw8N1j5Ep0QzzTj4C9O6nSgyuN+ZSFncPeRcVq2IZfzdgzi9ontMbTTMsK1Vmu3WE29c6Wn8/bF5INHn2Fx40KCkPfCmTlorQCyau4u7cQAEHgZR/5OLl1Y4emRT0NFIGBAVvwosAQIBt1C0XeY82iuEO2l5tIMmPT+UnfEZ/s5lFaDR50+qteLCxa+6kPoOZFl0kukPcSi3++gfdtRsElRzoDUlGR8jEQAztlhurvsmaWvtt0/dlRkccu6AnHsH2+pAWyY4AfVwr3spb6A7kT3MLdOC6iPTOtjsxyOuSP48OeYJGPc4P9kNj/eOMU6ErACCi6ib2UnyitIX67mqzIj6sdkrnWQNilkmH8GIwlHyI6PvWY8eDPuvyrQUy2ICvmDw3jzA="
